name: Update Activity Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

concurrency:
  group: output-branch
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: ${{ github.repository_owner }}

          options: |
            {
              "theme": "merko",
              "bg_color": "0a0f0b",
              "border_color": "e4e2e2",
              "title_color": "abd200",
              "color": "68b587",
              "line": "abd200",
              "point": "b7d364",
              "area": true,
              "area_color": "abd200",
              "radius": 5,
              "days": 31,
              "custom_title": "GitHub Activity"
            }

          output_path: dist/activity-graph.svg

          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish activity graph
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
